hicseg_template = "install.packages('HiCseg')"
"library(HiCseg)"
"matrix = as.matrix(read.table(file={},sep='\t',header=F,stringsAsFactors=F))"
"dim=dim(matrix)"
"n=dim[1]"
"result = HiCseg_linkC_R(n,round(n/3), {}, matrix,'D')"
"write.table(result, 'buff_hicseg.txt', sep='\t', quote=F)"
"results<-read.table('buff_hicseg.txt', header=T, sep='\t', stringsAsFactors=F)"
"options(scipen=999)"
"res<-{}"
"results_trim<-results[results$t_hat!=0,]"
"TADs<-data.frame('start'=(results_trim$t_hat[-(nrow(results_trim))]*res),'end'=(results_trim$t_hat[-1]*res))"
"write.table(TADs, file={}, quote=FALSE, sep='\t', row.names = FALSE, col.names = FALSE)"

